<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Failed suite [CreditCardAuthCapRefund]">
  <parameter name="tech" value="woocommerce"/>
  <parameter name="prefix" value="credit.card.refund."/>
  <parameter name="testscenario" value="positive"/>
  <test thread-count="5" name="CreditCardAuthCapRefund(failed)">
    <classes>
      <class name="com.cybersource.test.woocommerce.CreditCard">
        <methods>
          <include name="init"/>
          <include name="executeAuthCapRefund" invocation-numbers="0"/>
        </methods>
      </class> <!-- com.cybersource.test.woocommerce.CreditCard -->
    </classes>
  </test> <!-- CreditCardAuthCapRefund(failed) -->
</suite> <!-- Failed suite [CreditCardAuthCapRefund] -->
